"""
my fav relays list
2023/03-05
"""

"""
NIP-11
 "name": <string identifying relay>,
 "description": <string with detailed information>,
 "pubkey": <administrative contact pubkey>,
 "contact": <administrative alternate contact>,
 "supported_nips": <a list of NIP numbers supported by the relay>,
 "software": <string identifying relay software URL>,
 "version": <string version identifier>
"""
nip_11_struct = [ "name","description","pubkey","contact","supported_nips","software","version"]
nip_11_struct_adv = [ "name","description","pubkey","contact","supported_nips","software","version","limitation"]



relays_list = [
"wss://relay.damus.io",
"wss://relay.plebstr.com",
"wss://nos.lol",
#"wss://nostr.mnethome.de",
#"wss://relay.snort.social/",
"wss://relay.nostr.ro",
"wss://nostr.petrkr.net/strfry",
#"wss://nostr.petrkr.net/nostream"
]


relays_list100 = [
"wss://relay.damus.io",
"wss://relay.plebstr.com",
"wss://relay.nostrplebs.com",
"wss://nostr.mnethome.de",
"wss://nostr-pub.wellorder.net",
"wss://at.nostrworks.com",
"wss://deschooling.us",
"wss://knostr.neutrine.com",
#"wss://node01.nostress.cc",
"wss://nostr.petrkr.net/strfry",
"wss://nos.lol",
"wss://nostr.anchel.nl",
"wss://no.str.cr",
"wss://eden.nostr.land",
"wss://nostr-01.bolt.observer",
"wss://nostr-1.nbo.angani.co",
"wss://nostr3.actn.io",
"wss://nostr.sidnlabs.nl",
"wss://nostr.wine",
"wss://nostr.8e23.net",
"wss://nostr.actn.io",
"wss://nostr.bch.ninja",
"wss://nostr.bitcoiner.social",
"wss://nostr.bongbong.com",
"wss://nostr.bostonbtc.com",
"wss://nostr.cercatrova.me",
"wss://nostr.coollamer.com",
"wss://nostr.corebreach.com",
"wss://nostr.delo.software",
"wss://nostr-dev.wellorder.net",
"wss://nostr.drss.io",
"wss://nostr.easydns.ca",
"wss://nostr.einundzwanzig.space",
"wss://nostrex.fly.dev",
"wss://nostr.fmt.wiz.biz",
"wss://nostr.gromeul.eu",
"wss://nostr.hackerman.pro",
"wss://nostr.handyjunky.com",
"wss://nostr.hugo.md",
"wss://nostrical.com",
"wss://nostrich.friendship.tw",
"wss://nostr.kollider.xyz",
"wss://nostr.lu.ke",
"wss://nostr.mikedilger.com",
"wss://nostr.milou.lol",
"wss://nostr.mom",
"wss://nostr.mouton.dev",
"wss://nostr.nodeofsven.com",
"wss://nostr.ownscale.org",
"wss://nostr.orangepill.dev",
"wss://nostr.oxtr.dev",
"wss://nostr-pub1.southflorida.ninja",
"wss://nostr-pub.wellorder.net",
"wss://nostr-relay.bitcoin.ninja",
"wss://nostr-relay.derekross.me",
"wss://nostr.zebedee.cloud",
"wss://nostr-relay.lnmarkets.com",
"wss://nostr-relay.schnitzel.world",
"wss://nostr.bitcoin.sex",
"wss://relay.nostrich.de",
"wss://nostr.roundrockbitcoiners.com",
"wss://nostr.screaminglife.io",
"wss://nostr.sectiontwo.org",
"wss://nostr.semisol.dev",
"wss://nostr.shawnyeager.net",
"wss://nostr.slothy.win",
"wss://nostr.supremestack.xyz",
"wss://nostr.swiss-enigma.ch",
"wss://nostr.uselessshit.co",
"wss://nostr-verified.wellorder.net",
"wss://nostr-verif.slothy.win",
"wss://nostr.vulpem.com",
"wss://nostr.w3ird.tech",
"wss://nostr.walletofsatoshi.com",
"wss://nostr.zaprite.io",
"wss://nostr.zebedee.cloud",
"wss://relay.current.fyi",
"wss://relay.cryptocculture.com",
"wss://relay.lexingtonbitcoin.org",
"wss://relay.ryzizub.com",
"wss://relay.n057r.club",
"wss://relay.nostr.au",
"wss://relay.nostr.band",
"wss://relay.nostr.bg",
"wss://nostramsterdam.vpx.moe",
"wss://relay.nostrgraph.net",
"wss://relay.nostrich.de",
"wss://relay.nostrid.com",
"wss://relay.nostr.nu",
"wss://relay.nostr.ro",
"wss://relay.nostr.scot",
"wss://relay.austrich.net",
"wss://relay.sendstr.com",
"wss://relay.snort.social",
"wss://relay.taxi",
"wss://relay-pub.deschooling.us",
"wss://relay.ryzizub.com",
"wss://nostr-01.dorafactory.org",
"wss://rsslay.nostr.moe",
"wss://sg.qemura.xyz",
"wss://paid.no.str.cr",
]


# ------------------------------
#"wss://relay.nostr.ch",
#"wss://nostr.onsats.org",
#"wss://lightningrelay.com",
#"wss://nostr.massmux.com",
#"wss://nostr.noones.com",
#"wss://nostr.relayer.se",
#"wss://nostr.rocks",
#"wss://relay.minds.com/nostr/v1/ws",
#"wss://relay.nvote.co",
#"wss://relay.nvote.co:443",
#"wss://rasca.asnubes.art",
#"wss://brb.io",
#"wss://public.nostr.swissrouting.com",
#"wss://nostr.sandwich.farm",
#"wss://relay.nostr.info",
#"wss://relay.nostr.express",
#"wss://nostr.middling.mydns.jp",


# https://api.nostr.watch/v1/online

relays_big_list = ["wss://relay.damus.io","wss://relay.honk.pw","wss://nostr-pub.wellorder.net","wss://nostr.mom","wss://nostr.slothy.win","wss://global.relay.red","wss://sg.qemura.xyz","wss://relay.stoner.com","wss://nostr.einundzwanzig.space","wss://nostr.cercatrova.me","wss://nostr.swiss-enigma.ch","wss://nos.lol","wss://relay.nostr.band","wss://nostr-relay.derekross.me","wss://nostr.drss.io","wss://no.str.cr","wss://nostr.bongbong.com","wss://relay.sendstr.com","wss://relay.cryptocculture.com","wss://relay.nostr.scot","wss://relay.taxi","wss://nostr.massmux.com","wss://nostr-relay.schnitzel.world","wss://relay.nostr.com.au","wss://knostr.neutrine.com","wss://nostr.nodeofsven.com","wss://nostrical.com","wss://nostr-relay.freedomnode.com","wss://nostr.gromeul.eu","wss://relay.nostr.ro","wss://relay.nostrich.de","wss://nostr.vulpem.com","wss://relay.ryzizub.com","wss://nostr3.actn.io","wss://nostr.bostonbtc.com","wss://nostr-verif.slothy.win","wss://nostr.supremestack.xyz","wss://relay.lexingtonbitcoin.org","wss://relay.nostr.moe","wss://nostr-1.nbo.angani.co","wss://nostr.coollamer.com","wss://nostr.mnethome.de","wss://relay.plebstr.com","wss://nostr.uselessshit.co","wss://relay.wellorder.net","wss://nostr.handyjunky.com","wss://relay-pub.deschooling.us","wss://nostr.easydns.ca","wss://relay.dwadziesciajeden.pl","wss://nostr-pub1.southflorida.ninja","wss://relay.orangepill.dev","wss://nostr.600.wtf","wss://nostr.mouton.dev","wss://e.nos.lol","wss://nostrich.friendship.tw","wss://nostream-production-5895.up.railway.app","wss://nostr.bitcoin.sex","wss://nostr-relay.texashedge.xyz","wss://nostr.thomascdnns.com","wss://nostr.btcmp.com","wss://relay.nostr.africa","wss://ragnar-relay.com","wss://nostr.zkid.social","wss://nostr.bitcoin-21.org","wss://nostr.com.de","wss://nostr.data.haus","wss://relay1.gems.xyz","wss://nostream.nostrly.io","wss://relay.austrich.net","wss://nostr.terminus.money","wss://nostr.0ne.day","wss://relay.valera.co","wss://nostr01.opencult.com","wss://nostr.wine","wss://nostr.koning-degraaf.nl","wss://nostr.pleb.network","wss://nostr.cheeserobot.org","wss://nostr.thank.eu","wss://relay.hamnet.io","wss://nostr.shroomslab.net","wss://nostr.truckenbucks.com","wss://zee-relay.fly.dev","wss://nostr.blockpower.capital","wss://nostr.sidnlabs.nl","wss://nostr-rs-relay.cryptoassetssubledger.com","wss://nostr.inosta.cc","wss://nostr21.com","wss://arc1.arcadelabs.co","wss://relay.nostr.distrl.net","wss://relay.zeh.app","wss://spore.ws","wss://relay.727whisky.com","wss://nostr.ch3n2k.com","wss://nostr.island.network","wss://relay.1bps.io","wss://relay.nostrview.com","wss://relay.nostromo.social","wss://offchain.pub","wss://relay.nostr.wirednet.jp","wss://nostream.unift.xyz","wss://jp-relay-nostr.invr.chat","wss://relay.humanumest.social","wss://nostr.21crypto.ch","wss://nostr.21l.st","wss://nostr.fennel.org:7000","wss://paid.spore.ws","wss://nostr.notmyhostna.me","wss://relay.arsip.my.id","wss://nostr.buythisdip.com","wss://arnostr.permadao.io","wss://rsr.uyky.net:30443","wss://nostr.l00p.org","wss://cheery-paddock-rsakdrtc35c55n6yregn.wnext.app","wss://lightningrelay.com","wss://no-str.wnhefei.cn:28443","wss://bitcoinmaximalists.online","wss://nostr.rocket-tech.net","wss://nostr.herci.one","wss://nostr-2.afarazit.eu","wss://relay.nostr.net.in","wss://private.red.gb.net","wss://nostr.walletofsatoshi.com","wss://relay.nostrid.com","wss://relay.nostr3.io","wss://nostr-relay.xbytez.io","wss://nostr.fluidtrack.in","wss://nostr.beta3.dev","wss://nostr.uthark.com","wss://nostr.cruncher.com","wss://nostr.foundrydigital.com","wss://nostr.chainofimmortals.net","wss://relay.nostrcheck.me","wss://nostr.rbel.co","wss://nostrelay.yeghro.site","wss://relay.nostr.vet","wss://nostr-relay.app.ikeji.ma","wss://nostro.cc","wss://nostr.yuv.al","wss://relay.lacosanostr.com","wss://lbrygen.xyz","wss://nostr.robotesc.ro","wss://relay.nostrdocs.com","wss://nostrue.com","wss://nostr.danvergara.com","wss://n.xmr.se","wss://nostr-us.coinfundit.com","wss://nostr-eu.coinfundit.com","wss://nostramsterdam.vpx.moe","wss://nproxy.kristapsk.lv","wss://nostr.topeth.info","wss://nostr.klabo.blog","wss://puravida.nostr.land","wss://nostr.bitcoiner.social","wss://relay.orange-crush.com","wss://nostr.bitcoinbay.engineering","wss://nostr.spaceshell.xyz","wss://nostr.screaminglife.io","wss://nostr.roundrockbitcoiners.com","wss://relay.f7z.io","wss://nostr.shawnyeager.net","wss://relay.nostriches.org","wss://nostr.arguflow.gg","wss://nostr-au.coinfundit.com","wss://relay.nostrology.org","wss://nostr.kollider.xyz","wss://nostr.bch.ninja","wss://nostr.8e23.net","wss://ch1.duno.com","wss://relay.nostrati.com","wss://nostr-dev.wellorder.net","wss://nostr-relay.nokotaro.com","wss://relay.snort.social","wss://nr.yay.so","wss://nostr.lu.ke","wss://nostr.anchel.nl","wss://atlas.nostr.land","wss://nostr.astrox.app","wss://nostr.ownbtc.online","wss://nostream.sh4.red","wss://relay.nostr.express","wss://nostr.fmt.wiz.biz","wss://nostr.actn.io","wss://nostr.688.org","wss://relay.nostrich.land","wss://global-relay.cesc.trade","wss://nostr.weking.tk","wss://nostr.zebedee.cloud","wss://nostr.pjv.me","wss://nostr-relay.lnmarkets.com","wss://relay.nostrgraph.net","wss://nostr-01.bolt.observer","wss://rsslay.nostr.moe","wss://nostrex.fly.dev","wss://eden.nostr.land","wss://nostr-verified.wellorder.net","wss://nostr.zaprite.io","wss://nostr.noones.com","wss://nostr.milou.lol","wss://relay.nostr.nu","wss://nostr.w3ird.tech","wss://nostr-relay.bitcoin.ninja","wss://paid.no.str.cr","wss://deschooling.us","wss://foolay.nostr.moe","wss://nostr.mikedilger.com","wss://freespeech.casa","wss://nostr.hugo.md","wss://relay.nvote.co","wss://bitcoiner.social","wss://klockenga.social","wss://nostr.1f52b.xyz","wss://nostr.sebastix.dev","wss://relay-verified.deschooling.us","wss://relay.alxgsv.com","wss://pow.nostrati.com","wss://n.wingu.se","wss://bhagos.org","wss://relay.nostr.hach.re","wss://nostr.asdf.mx","wss://nostr.bitcoinplebs.de","wss://nostr.goller.net","wss://nostr.corebreach.com","wss://nostr01.vida.dev","wss://nostr.localhost.re","wss://tmp-relay.cesc.trade","wss://nostr.plebchain.org","wss://nostr.mutinywallet.com","wss://nostr.decentony.com","wss://nostr.easify.de","wss://nostr.tools.global.id","wss://nostr.raitisoja.net","wss://nostrsatva.net","wss://xmr.usenostr.org","wss://nostr.naut.social","wss://at.nostrworks.com","wss://nostr.sovbit.host","wss://nostr.1sat.org","wss://nostr.hrmb.org","wss://nostr.bitocial.xyz","wss://relay.leesalminen.com","wss://relay.mrjohnsson.net","wss://mastodon.cloud/api/v1/streaming","wss://nostr.256k1.dev","wss://relay.beta.fogtype.com","wss://nostr.frostr.xyz","wss://frighteningdeafeningagent.nailuogg.repl.co","wss://rsslay.ch3n2k.com","wss://nostr.21sats.net","wss://nostr.rocketnode.space","wss://relay.nostr.bg","wss://nostr.malin.onl","wss://nostr.reamde.dev","wss://nostr-01.dorafactory.org","wss://nostr.globals.fans","wss://nostr.oxtr.dev","wss://nostr.fractalized.ovh","wss://rsslay.data.haus","wss://nostr.primz.org","wss://relay.nostr.au","wss://nostr-mv.ashiroid.com","wss://relay.johnnyasantos.com","wss://relay.n057r.club","wss://nostr.mjex.me","wss://slick.mjex.me","wss://nostr.vpn1.codingmerc.com","wss://nos.qghs.in","wss://nostr.fediverse.jp","wss://nostr.lorentz.is","wss://nostr-pub.semisol.dev","wss://nostr.ownscale.org","wss://nostr.semisol.dev","wss://nostr.rocks","wss://nostr.delo.software","wss://nostr.orangepill.dev","wss://nostr.pinkanki.org","wss://relay.s3x.social","wss://btcpay.kukks.org/nostr/ws"]
